ctools.relationship:
  type: mapping
  label: 'Relationship'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'

condition.plugin.entity_bundle:*:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string

ctools.block_plugin.*:
  type: block.settings.[id]
  mapping:
    region:
      type: string
      label: 'Region'
    weight:
      type: integer
      label: 'Weight'
    uuid:
      type: string
      label: 'UUID'
    context_mapping:
      type: sequence
      label: 'Context assignments'
      sequence:
        - type: string

ctools.block_display_variant:
  type: display_variant.plugin
  label: 'Block display variant'
  mapping:
    selection_logic:
      type: string
      label: 'Selection logic'
    selection_conditions:
      type: sequence
      label: 'Selection Conditions'
      sequence:
        - type: condition.plugin.[id]
          label: 'Selection Condition'
    blocks:
      type: sequence
      label: 'Blocks'
      sequence:
        - type: ctools.block_plugin.[id]
